config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
resources :users, only: [:show] do
resources :posts, only: [:show,:index, :new, :create] do 
resources :comments, only:[:new, :create]
resources :likes, only:[:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  after_create :update_counter

  def update_counter
    if !post.comment_counter
      post.comment_counter = 1
      post.save
    else
      post.comment_counter += 1
      post.save
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  after_create :update_counter

  def update_counter
    if !post.likes_counter
      post.likes_counter = 1
      post.save
    else
      post.likes_counter += 1
      post.save
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes
  has_many :comments, foreign_key: 'post_id'
  belongs_to :user, class_name: 'User'
  after_create :update_counter
  validates :title, presence: true, length: { minimum: 2, maximum: 250 }
  validates :comment_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_counter
    if !user.posts_counter
      user.posts_counter = 1
      user.save
    else
      user.posts_counter += 1
      user.save
    end
  end

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'user_id'
  has_many :comments
  has_many :likes
  validates :name, presence: true, length: { minimum: 2, maximum: 55 }
  def recent_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[photo posts_counter])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    @comment = Comment.new(params.require(:comment).permit(:text))
    @post = Post.find(params[:post_id])
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    @comment.save
    redirect_to "/users/#{current_user.id}/posts/#{@post.id}"
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new()
    @post = Post.find(params[:post_id])
    @like.user_id = current_user.id
    @like.post_id = @post.id
    @like.save
    redirect_to "/users/#{current_user.id}/posts"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @comments = @post.recent_comments
    @user = @post.user
  end

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(user_id: @user.id)
  end

  def new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :text))
    @post.comment_counter = 0
    @post.likes_counter = 0
    current_user.posts << @post
    redirect_to user_post_path(current_user, @post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with scope: :comment, url: user_post_comments_path, local: true do |f|  %>
  <p>
  <%= f.label :text %> <br>
  <%= f.text_area :text %>
  </p>

  <p>
  <%= f.submit%>
  </p>
  
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Post Index Page</h1>
<div>
  <h2>User</h2>
  <img src="<%= @user.photo %>" alt="User Img" />
  <span><%= @user.name %></span>
  <span><%= @user.posts_counter %></span>
</div>
<div>
  <h2>Posts</h2>
  <ol>
    <% @posts.each do |post| %>
    <li>
      <p>
        <a
          href="http://localhost:3000/users/<%= @user.id %>/posts/<%= post.id %>"
          ><%= post.title%></a
        >
      </p>
      <p><%= post.text%></p>
      <p>number on comments:<%= post.comment_counter || 0 %></p>
      <p>number on likes:<%= post.likes_counter || 0 %></p>
      <p><a href="<%= new_user_post_comment_path(@user,post) %>"> Add Comment </a></p>
      <p>  <%= form_with scope: :like, url: user_post_likes_path(@user,post), local: true do |f|  %>
        <p>
        <%= f.submit%>
        </p>
        <% end %></p>
    </li>
    <% end %>
  </ol>
</div>
<h3><a href="http://localhost:3000/users/<%= @user.id %>/posts/new">Create Post</a></h3>

app/views/posts/new.html.erb
<%= form_with scope: :post, url:  user_posts_path, local: true do |f|  %>
  <p>
  <%= f.label :title %> <br>
  <%= f.text_field :title %>
  </p>
  
  <p>
  <%= f.label :text %>
  <%= f.text_area :text %>
  </p>
  
  <p>
  <%= f.submit%>
  </p>
  
  
  
  <% end %>

app/views/posts/show.html.erb
<h1>Post details Page</h1>

<div>
<p><%= @post.user.name%></p>
<p><%= @post.title%></p>
<p><%= @post.text%></p>
<p>number on comments:<%= @post.comment_counter || 0%></p>
<p>number on likes:<%= @post.likes_counter || 0%></p>
</div>
<div>
<ul>
<% @comments.each do |comment| %>
<li><span><%= comment.user.name%></span>: <%= comment.text %></li>
<% end %>

<li>
<%= form_with scope: :like, url: user_post_likes_path(@user,@post), local: true do |f|  %>
  <p>
  <%= f.submit "Like" %>
  </p>
  <% end %>
</li>

</ul>
</div>

app/views/users/index.html.erb
<h1>List of User "Index Page"</h1>
<ul>
<li>
<%= link_to "Sign In", new_user_session_path %>
</li>
<li><%= link_to "Sign Up", new_user_registration_path %>
</li>
<li>
<%= link_to "Sign Out", destroy_user_session_path %>
</li>
</ul>
<table style="width: 100%">
  <thead>
    <tr>
      <td><strong>Image</strong></td>
      <td><strong>Name</strong></td>
      <td><strong>Number of Posts</strong></td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <img src="#{<%= user.photo %>}" alt="User Img" />
      </td>
      <td><a href="http://localhost:3000/users/<%= user.id %>"><%= user.name %></a></td>
      <td><%= user.posts_counter || 0 %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>User Detials "Show Page"</h1>
<div>
<h2>User</h2>
  <img src="#{<%= @user.photo %>}" alt="User Img" />
  <span><%= @user.name %></span>
  <span><%= @user.posts_counter || 0 %></span>
</div>
<div>
<h2>Bio</h2>
  <p> <%= @user.bio || "the bio is embty" %></p>
</div>
<div>
<h2>Posts</h2>
<ol>
<% @posts.each do |post| %>
<li>
<p><%= post.title%></p>
<p><%= post.text%></p>
<p>number on comments:<%= post.comment_counter || 0%></p>
<p>number on likes:<%= post.likes_counter || 0%></p>
</li>
<% end %>
</ol>
<a href="http://localhost:3000/users/<%= @user.id %>/posts">See All Posts</a>
</div>